# ==================================================================================================
# GridWars Configuration
# ==================================================================================================
gridwars:
    directories:
        # Default value, should be provided upon start by a system property.
        baseWorkDir: 'work'
    registration:
        enabled: true
        registrationPassword: '123'
    matches:
        botUploadEnabled: true
        matchCountPerOpponent: 1
        workerCount: 2
        workerHeapSize: 256m
        # Give it a few more seconds than the general match timeout defined in the implementation
        # package. Just to be a bit more tolerant over the match execution overhead and bot
        # initialisation.
        executionTimeoutSeconds: 80
    mail:
        enabled: true
        from: 'CERN GridWars <grid.wars@cern.ch>'
        bccRecipient: 'benjamin.wolff@cern.ch'

---
spring:
    profiles: dev

gridwars:
    mail:
        toRecipientOverride: 'benjamin.wolff@cern.ch'
        baseUrl: 'http://localhost:8080'

---
spring:
    profiles: prod

gridwars:
    mail:
        baseUrl: 'http://gridwars.cern.ch'

# ==================================================================================================
# Spring Profile Configuration
# ==================================================================================================
---
spring:
    profiles:
        # Default profile that will be active. Must be overridden by a start parameter when running
        # in production.
        active: dev

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
---
spring:
    #profiles: dev
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    # TODO enable a file-based db for prod environment

# ==================================================================================================
# JPA Configuration
# ==================================================================================================
---
spring:
    jpa:
        open-in-view: true # TODO check what the effect on the transactions is during view rendering
        # Can be enabled for debugging
        show-sql: false

# ==================================================================================================
# Spring MVC Configuration
# ==================================================================================================
---
spring:
    mvc:
        static-path-pattern: /static/**

# ==================================================================================================
# Static Resources Configuration
# ==================================================================================================
---
spring:
    resources:
        static-locations: classpath:/static/
        cache:
            cachecontrol:
                max-age: 1d

# ==================================================================================================
# Spring Servlet Configuration
# ==================================================================================================
---
spring:
    servlet:
        multipart:
            # Maximum file upload size
            max-file-size: 5MB
            max-request-size: 8MB

# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
---
spring:
    profiles: dev
    thymeleaf:
        cache: false

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
---
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2
            settings:
                web-allow-others: true

# ==================================================================================================
# Server Configuration
# ==================================================================================================
---
server:
    compression:
        enabled: true
    tomcat:
        accesslog:
            enabled: true

# ==================================================================================================
# Mail Configuration
# ==================================================================================================
---
spring:
    mail:
        host: smtp.cern.ch
        port: 587
        username: gridwars
        password: Fiba-Raxi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
