# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
spring:
    thymeleaf:
        cache: false

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
spring:
    datasource:
        url: jdbc:h2:mem:testdb

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2
