# ==================================================================================================
# Spring Profiles Configuration
# ==================================================================================================
spring:
    profiles:
        active: dev

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
---
spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE


# ==================================================================================================
# JPA Configuration
# ==================================================================================================
---
spring:
    jpa:
        # Disable OSIV, we rely on the transactional annotations for transactions management.
        open-in-view: false

# ==================================================================================================
# Spring MVC Configuration
# ==================================================================================================
---
spring:
    mvc:
        static-path-pattern: /static/**

# ==================================================================================================
# Static Resources Configuration
# ==================================================================================================
---
spring:
    resources:
        static-locations: classpath:/static/
        cache:
            cachecontrol:
                max-age: 1h

# ==================================================================================================
# Spring Servlet Configuration
# ==================================================================================================
---
spring:
    servlet:
        multipart:
            max-file-size: 5MB # Maximum file upload size
            #max-file-size: 3KB
            #max-request-size: 5MB

# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
---
spring:
    thymeleaf:
        cache: false

# ==================================================================================================
# Quartz Configuration
# ==================================================================================================
---
spring:
    quartz:
        job-store-type: memory
        jdbc:
            initialize-schema: never

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
---
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2

# ==================================================================================================
# Server Configuration
# ==================================================================================================
---
server:
    compression:
        enabled: true
    tomcat:
        accesslog:
            enabled: true

# ==================================================================================================
# Mail Configuration
# ==================================================================================================
---
spring:
    mail:
        host: smtp.cern.ch
        port: 587
        username: gridwars
        password: Fiba-Raxi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000

# ==================================================================================================
# GridWars Configuration
# ==================================================================================================
---
gridwars:
    directories:
        # Default value, should be provided upon start by a system property.
        baseWorkDir: './work'
    matches:
        number: 1
        workerCount: 3
        # TODO adjust the value below to a more realistic value. theoretically, a match can last 120 seconds, plus some millis for initialisation
        executionTimeoutSeconds: 5
        # Class name must correspond to the main class in the "core/runtime" sub-project
        matchRuntimeMainClassName: 'cern.ais.gridwars.runtime.MatchRuntime'
    mail:
        from: 'CERN GridWars <grid.wars@cern.ch>'
        bcc: 'benjamin.wolff@cern.ch'
