# ==================================================================================================
# Spring Profiles Configuration
# ==================================================================================================
spring:
    profiles:
        active: dev

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
---
spring:
    datasource:
        url: jdbc:h2:mem:testdb

# ==================================================================================================
# Spring MVC Configuration
# ==================================================================================================
---
spring:
    mvc:
        static-path-pattern: /static/**

# ==================================================================================================
# Static Resources Configuration
# ==================================================================================================
---
spring:
    resources:
        static-locations: classpath:/static/
        cache:
            cachecontrol:
                max-age: 1h

# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
---
spring:
    thymeleaf:
        cache: false

# ==================================================================================================
# Quartz Configuration
# ==================================================================================================
---
spring:
    quartz:
        job-store-type: memory
        jdbc:
            initialize-schema: never

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
---
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2

# ==================================================================================================
# Server Configuration
# ==================================================================================================
---
server:
    compression:
        enabled: true
