# ==================================================================================================
# Spring Profiles Configuration
# ==================================================================================================
spring:
    profiles:
        active: dev

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
---
spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE

# ==================================================================================================
# Spring MVC Configuration
# ==================================================================================================
---
spring:
    mvc:
        static-path-pattern: /static/**

# ==================================================================================================
# Static Resources Configuration
# ==================================================================================================
---
spring:
    resources:
        static-locations: classpath:/static/
        cache:
            cachecontrol:
                max-age: 1h

# ==================================================================================================
# Spring Servlet Configuration
# ==================================================================================================
---
spring:
    servlet:
        multipart:
            max-file-size: 5MB # Maximum file upload size
            #max-file-size: 3KB
            #max-request-size: 5MB

# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
---
spring:
    thymeleaf:
        cache: false

# ==================================================================================================
# Quartz Configuration
# ==================================================================================================
---
spring:
    quartz:
        job-store-type: memory
        jdbc:
            initialize-schema: never

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
---
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2

# ==================================================================================================
# Server Configuration
# ==================================================================================================
---
server:
    compression:
        enabled: true
    tomcat:
        accesslog:
            enabled: true

# ==================================================================================================
# GridWars Configuration
# ==================================================================================================
---
gridwars:
    workDir: '../'
    matches:
        number: 5
