# ==================================================================================================
# GridWars Configuration
# ==================================================================================================
gridwars:
    directories:
        # Default value, should be provided upon start by a system property.
        baseWorkDir: 'work'
    matches:
        matchCountPerOpponent: 1
        workerCount: 2
        workerHeapSize: 256m
        executionTimeoutSeconds: 70 # TODO adjust the value below to a more realistic value
    mail:
        enabled: true
        from: 'CERN GridWars <grid.wars@cern.ch>'
        bcc: 'benjamin.wolff@cern.ch'
        toRecipientOverride: 'benjamin.wolff@cern.ch'

# ==================================================================================================
# Spring Profiles Configuration
# ==================================================================================================
---
spring:
    profiles:
        # Default profile that will be active. Must be overridden by a start parameter when running
        # in production.
        active: dev

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
---
spring:
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE


# ==================================================================================================
# JPA Configuration
# ==================================================================================================
---
spring:
    jpa:
        open-in-view: true # TODO check what the effect on the transactions is during view rendering
        # Enable for debugging
        show-sql: false

# ==================================================================================================
# Spring MVC Configuration
# ==================================================================================================
---
spring:
    mvc:
        static-path-pattern: /static/**

# ==================================================================================================
# Static Resources Configuration
# ==================================================================================================
---
spring:
    resources:
        static-locations: classpath:/static/
        cache:
            cachecontrol:
                max-age: 1d

# ==================================================================================================
# Spring Servlet Configuration
# ==================================================================================================
---
spring:
    servlet:
        multipart:
            # Maximum file upload size
            max-file-size: 5MB
            #max-file-size: 3KB
            max-request-size: 8MB

# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
---
spring:
    thymeleaf:
        # TODO disable caching only in dev mode...
        cache: false

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
---
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2
            settings:
                web-allow-others: true

# ==================================================================================================
# Server Configuration
# ==================================================================================================
---
server:
    compression:
        enabled: true
    tomcat:
        accesslog:
            enabled: true

# ==================================================================================================
# Mail Configuration
# ==================================================================================================
---
spring:
    mail:
        host: smtp.cern.ch
        port: 587
        username: gridwars
        password: Fiba-Raxi
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enabled: true
                        required: true
                    connectiontimeout: 5000
                    timeout: 3000
                    writetimeout: 5000
