# ==================================================================================================
# Thymeleaf Configuration
# ==================================================================================================
spring:
    thymeleaf:
        cache: false

# ==================================================================================================
# DataSource Configuration
# ==================================================================================================
spring:
    datasource:
        url: jdbc:h2:mem:testdb

# ==================================================================================================
# Quartz Configuration
# ==================================================================================================
spring:
    quartz:
        job-store-type: memory
        # TODO disabling the schema below doesn't work...
        jdbc:
            initialize-schema: never

# ==================================================================================================
# H2 Configuration
# ==================================================================================================
spring:
    h2:
        console:
            enabled: true
            path: /admin/h2
